name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-project-id
          # Additional configuration options as needed

      - name: Save GCP service account key
        run: |
          mkdir -p .secure_files
          echo "${{ secrets.GCP_SA_KEY }}" > .secure_files/abacus-apigee-demo-a9fffc7cc15c.json

      - name: Download secure files
        env:
          GITLAB_AUTH_TOKEN: ${{ secrets.GITLAB_AUTH_TOKEN }}  # Adjust token name as per requirement
        run: |
          curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
          download-secure-files --auth-token $GITLAB_AUTH_TOKEN

      - name: Execute custom script
        run: |
          # Your custom script execution steps here
